version: '3'

services:
  ravendb:
    image: ravendb/ravendb
    ports:
      - '8080:8080'
      - '38888:38888'
    env_file: .ravendb.env
    volumes:
      - './ravendb/config:/opt/RavenDB/config'
      - './ravendb/data:/opt/RavenDB/Server/RavenData'
    networks:
      - default

networks:
  default:
    driver: bridge
