version: '3'

services:
  ravendb:
    image: ravendb/ravendb
    ports:
      - '8080:8080'
    environment:
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_Setup_Mode=None
    networks:
      - default

networks:
  default:
    driver: bridge
